#!/usr/bin/env node
/**
 * Reads all markdown content from lib/knowledge/{system,data,lide,strategie,provoz,icp}/*.md
 * and writes typed TS modules:
 *   - lib/ai/system-prompts.generated.ts  (BRAND_VOICE, OUTPUT_FORMAT)
 *   - lib/knowledge/cards.generated.ts    (CARDS: Card[])
 *
 * Eliminates runtime fs.readFile / readdir for production code path,
 * which avoids Vercel includeFiles glob fragility for .md content.
 *
 * Run via `pnpm build:content` or as part of `pnpm vercel-build`.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const knowledgeDir = path.join(projectRoot, 'lib', 'knowledge');

const DIMENSIONS = ['data', 'lide', 'strategie', 'provoz', 'icp'];
const SYSTEM_FILES = ['brand-voice', 'output-format'];

const banner = `// AUTOGENERATED by scripts/build-content.mjs — do not edit by hand.
// Source: lib/knowledge/**/*.md`;

async function buildSystemPrompts() {
  const systemDir = path.join(knowledgeDir, 'system');
  const map = {};
  for (const name of SYSTEM_FILES) {
    const filepath = path.join(systemDir, `${name}.md`);
    map[name] = await readFile(filepath, 'utf-8');
  }

  const moduleSource = `${banner}

export const BRAND_VOICE = ${JSON.stringify(map['brand-voice'])};

export const OUTPUT_FORMAT = ${JSON.stringify(map['output-format'])};
`;
  const outPath = path.join(projectRoot, 'lib', 'ai', 'system-prompts.generated.ts');
  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, moduleSource);
  return outPath;
}

async function buildCards() {
  const cards = [];
  for (const dim of DIMENSIONS) {
    const dimPath = path.join(knowledgeDir, dim);
    let entries;
    try {
      entries = await readdir(dimPath);
    } catch (err) {
      if (err.code === 'ENOENT') continue;
      throw err;
    }
    for (const entry of entries.sort()) {
      if (!entry.endsWith('.md')) continue;
      const filepath = path.join(dimPath, entry);
      const raw = await readFile(filepath, 'utf-8');
      const { data, content } = matter(raw);
      const frontmatter = { ...data, id: data.id ?? path.basename(entry, '.md') };
      cards.push({
        frontmatter,
        body: content.trim(),
        filepath: `${dim}/${entry}`,
      });
    }
  }

  const moduleSource = `${banner}
import type { Card } from './types.js';

export const CARDS: Card[] = ${JSON.stringify(cards, null, 2)};
`;
  const outPath = path.join(knowledgeDir, 'cards.generated.ts');
  await writeFile(outPath, moduleSource);
  return { path: outPath, count: cards.length };
}

async function main() {
  const systemPath = await buildSystemPrompts();
  const { path: cardsPath, count } = await buildCards();
  console.log(`[build-content] wrote ${path.relative(projectRoot, systemPath)} (2 prompts)`);
  console.log(`[build-content] wrote ${path.relative(projectRoot, cardsPath)} (${count} cards)`);
}

main().catch((err) => {
  console.error('[build-content] failed:', err);
  process.exit(1);
});
