#!/usr/bin/env node
/**
 * Reads all markdown content from lib/knowledge/{system,data,lide,strategie,provoz,icp}/*.md
 * and TTF fonts from lib/pdf/fonts/*.ttf, then writes typed TS modules:
 *   - lib/ai/system-prompts.generated.ts  (BRAND_VOICE, OUTPUT_FORMAT)
 *   - lib/knowledge/cards.generated.ts    (CARDS: Card[])
 *   - lib/pdf/fonts.generated.ts          (INTER_DATAURL, NOTOSERIF_DATAURL)
 *
 * Eliminates runtime fs.readFile / readdir for production code path,
 * which avoids Vercel includeFiles glob fragility for non-JS assets.
 *
 * Run via `pnpm build:content` or as part of `pnpm vercel-build`.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const knowledgeDir = path.join(projectRoot, 'lib', 'knowledge');
const fontsDir = path.join(projectRoot, 'lib', 'pdf', 'fonts');

const DIMENSIONS = ['data', 'lide', 'strategie', 'provoz', 'icp'];
const SYSTEM_FILES = ['brand-voice', 'output-format'];
const FONT_FILES = [
  { name: 'INTER', file: 'Inter.ttf' },
  { name: 'NOTOSERIF', file: 'NotoSerif.ttf' },
];

const banner = `// AUTOGENERATED by scripts/build-content.mjs — do not edit by hand.
// Source: lib/knowledge/**/*.md, lib/pdf/fonts/*.ttf`;

async function buildSystemPrompts() {
  const systemDir = path.join(knowledgeDir, 'system');
  const map = {};
  for (const name of SYSTEM_FILES) {
    const filepath = path.join(systemDir, `${name}.md`);
    map[name] = await readFile(filepath, 'utf-8');
  }

  const moduleSource = `${banner}

export const BRAND_VOICE = ${JSON.stringify(map['brand-voice'])};

export const OUTPUT_FORMAT = ${JSON.stringify(map['output-format'])};
`;
  const outPath = path.join(projectRoot, 'lib', 'ai', 'system-prompts.generated.ts');
  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, moduleSource);
  return outPath;
}

async function buildCards() {
  const cards = [];
  for (const dim of DIMENSIONS) {
    const dimPath = path.join(knowledgeDir, dim);
    let entries;
    try {
      entries = await readdir(dimPath);
    } catch (err) {
      if (err.code === 'ENOENT') continue;
      throw err;
    }
    for (const entry of entries.sort()) {
      if (!entry.endsWith('.md')) continue;
      const filepath = path.join(dimPath, entry);
      const raw = await readFile(filepath, 'utf-8');
      const { data, content } = matter(raw);
      const frontmatter = { ...data, id: data.id ?? path.basename(entry, '.md') };
      cards.push({
        frontmatter,
        body: content.trim(),
        filepath: `${dim}/${entry}`,
      });
    }
  }

  const moduleSource = `${banner}
import type { Card } from './types.js';

export const CARDS: Card[] = ${JSON.stringify(cards, null, 2)};
`;
  const outPath = path.join(knowledgeDir, 'cards.generated.ts');
  await writeFile(outPath, moduleSource);
  return { path: outPath, count: cards.length };
}

async function buildFonts() {
  const entries = [];
  for (const { name, file } of FONT_FILES) {
    const filepath = path.join(fontsDir, file);
    const buf = await readFile(filepath);
    const b64 = buf.toString('base64');
    entries.push({ name, b64, size: buf.byteLength });
  }

  const lines = [banner, ''];
  for (const { name, b64 } of entries) {
    lines.push(`export const ${name}_DATAURL = "data:font/ttf;base64,${b64}";`);
  }
  const moduleSource = lines.join('\n') + '\n';
  const outPath = path.join(projectRoot, 'lib', 'pdf', 'fonts.generated.ts');
  await writeFile(outPath, moduleSource);
  return { path: outPath, entries };
}

async function main() {
  const systemPath = await buildSystemPrompts();
  const { path: cardsPath, count } = await buildCards();
  const { path: fontsPath, entries: fontEntries } = await buildFonts();
  console.log(`[build-content] wrote ${path.relative(projectRoot, systemPath)} (2 prompts)`);
  console.log(`[build-content] wrote ${path.relative(projectRoot, cardsPath)} (${count} cards)`);
  const fontSummary = fontEntries.map((e) => `${e.name} ${Math.round(e.size / 1024)}KB`).join(', ');
  console.log(`[build-content] wrote ${path.relative(projectRoot, fontsPath)} (${fontSummary})`);
}

main().catch((err) => {
  console.error('[build-content] failed:', err);
  process.exit(1);
});
